### ISSUE TITLE
Adding this repo to the SD Auto1111

### ISSUE THREAD

**Issue by p0mad** [huchenlei/stable-diffusion-ps-pea#3]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

Hi, I want to do exactly the same process as the image
https://user-images.githubusercontent.com/20929282/256951742-5dcb6d6f-5c3e-4cf8-abf6-c5223059a8af.png
into the auto1111 but without using external applications like photoshop /pea.

Actually i want to concatenate controlnet Pose ( openpose as a unit0 of ControlNet) and CN canny (canny as a unit1 of Controlnet)
but not just the whole canny image, just the hands part!

is it possible to use this repo?
any guide or insight in that regards would be much appritiated

Thnaks
Best regards

### Steps to reproduce the problem

1. Go to Auto1111, ControlNet tabs and add openpose and canny Model
2. edit canny Model to just include hand parts!
3. Auto detect hands to be used in canny CN unit1 for video generation

### What should have happened?

autodetect hands and just use those parts for canny!

### Commit where the problem happens

webui: 
stable-diffusion-ps-pea: [Previous good version]

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
no
```

**Comment by huchenlei** [comment]
Currently you can use  https://github.com/yankooliveira/sd-webui-photopea-embed to send preprocessor maps to ControlNet (You can specify which unit to send to).

I think autodetection of hand is out of current scope of the extension here, as the extension does not have capability of invoking an hand detection algorithm in the browser. There need to be some sort of backend implementation in A1111 to do that first.
